const char* html_page = 
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <title>Hexagon Color Picker</title>\n"
"    <style>\n"
"        body {\n"
"            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
"            display: flex;\n"
"            flex-direction: column;\n"
"            justify-content: center;\n"
"            align-items: center;\n"
"            height: 100vh;\n"
"            margin: 0;\n"
"            background-color: #f5f5f5;\n"
"        }\n"
"        \n"
"        h1 {\n"
"            margin-bottom: 20px;\n"
"            font-size: 24px;\n"
"            color: #333;\n"
"        }\n"
"        \n"
"        .container {\n"
"            display: grid;\n"
"            grid-template-columns: repeat(5, 64px);\n"
"            gap: 6px;\n"
"            margin-bottom: 20px;\n"
"        }\n"
"        \n"
"        .hexagon {\n"
"            width: 60px;\n"
"            height: 34.64px;\n"
"            position: relative;\n"
"            margin: 17.32px 0;\n"
"            clip-path: polygon(50% 0%, 100% 25%, 100% 75%, 50% 100%, 0% 75%, 0% 25%);\n"
"            transition: transform 0.2s, box-shadow 0.2s;\n"
"            cursor: pointer;\n"
"        }\n"
"        \n"
"        .hexagon:hover {\n"
"            transform: scale(1.1);\n"
"            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);\n"
"        }\n"
"        \n"
"        .hexagon:nth-child(odd) {\n"
"            margin-top: 0;\n"
"        }\n"
"        \n"
"        .hexagon[data-color=\"#ff0000\"] { background-color: #ff0000; }\n"
"        .hexagon[data-color=\"#00ff00\"] { background-color: #00ff00; }\n"
"        .hexagon[data-color=\"#0000ff\"] { background-color: #0000ff; }\n"
"        .hexagon[data-color=\"#ffff00\"] { background-color: #ffff00; }\n"
"        .hexagon[data-color=\"#ff00ff\"] { background-color: #ff00ff; }\n"
"        .hexagon[data-color=\"#00ffff\"] { background-color: #00ffff; }\n"
"        .hexagon[data-color=\"#ff8800\"] { background-color: #ff8800; }\n"
"        .hexagon[data-color=\"#0088ff\"] { background-color: #0088ff; }\n"
"        .hexagon[data-color=\"#88ff00\"] { background-color: #88ff00; }\n"
"        .hexagon[data-color=\"#8800ff\"] { background-color: #8800ff; }\n"
"        \n"
"        #colorDisplay {\n"
"            padding: 10px;\n"
"            border-radius: 8px;\n"
"            border: 2px solid #ddd;\n"
"            width: 120px;\n"
"            line-height: 1.5;\n"
"            font-weight: bold;\n"
"            font-size: 16px;\n"
"            color: #333;\n"
"            background-color: #ffffff;\n"
"            text-align: center;\n"
"            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);\n"
"        }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <h1>Lucine per il tuo mood</h1>\n"
"    <div class=\"container\">\n"
"        <div class=\"hexagon\" data-color=\"#ff0000\"></div>\n"
"        <div class=\"hexagon\" data-color=\"#00ff00\"></div>\n"
"        <div class=\"hexagon\" data-color=\"#0000ff\"></div>\n"
"        <div class=\"hexagon\" data-color=\"#ffff00\"></div>\n"
"        <div class=\"hexagon\" data-color=\"#ff00ff\"></div>\n"
"        <div class=\"hexagon\" data-color=\"#00ffff\"></div>\n"
"        <div class=\"hexagon\" data-color=\"#ff8800\"></div>\n"
"        <div class=\"hexagon\" data-color=\"#0088ff\"></div>\n"
"        <div class=\"hexagon\" data-color=\"#88ff00\"></div>\n"
"        <div class=\"hexagon\" data-color=\"#8800ff\"></div>\n"
"    </div>\n"
"    <div id=\"colorDisplay\">Selected Color</div>\n"
"    \n"
"    <script>\n"
"        // Function to convert hex to RGB\n"
"        function hexToRgb(hex) {\n"
"            // Remove the hash at the start if it's there\n"
"            hex = hex.replace(/^#/, '');\n"
"            \n"
"            // Parse the hex string\n"
"            let r = parseInt(hex.substring(0, 2), 16);\n"
"            let g = parseInt(hex.substring(2, 4), 16);\n"
"            let b = parseInt(hex.substring(4, 6), 16);\n"
"            \n"
"            return `rgb(${r},${g},${b})`;\n"
"        }\n"
"        \n"
"        const hexagons = document.querySelectorAll('.hexagon');\n"
"        const colorDisplay = document.getElementById('colorDisplay');\n"
"        \n"
"        hexagons.forEach(hexagon => {\n"
"            hexagon.addEventListener('click', (event) => {\n"
"                const selectedColor = event.target.getAttribute('data-color');\n"
"                const rgbColor = hexToRgb(selectedColor);\n"
"                \n"
"                colorDisplay.style.backgroundColor = rgbColor;\n"
"                colorDisplay.textContent = rgbColor;\n"
"                \n"
"                // Create URL with RGB values\n"
"                const url = `http://192.168.1.151/color?r${encodeURIComponent(rgbColor.split(',')[0].split('(')[1])}g${encodeURIComponent(rgbColor.split(',')[1])}b${encodeURIComponent(rgbColor.split(',')[2].split(')')[0])}&`;\n"
"                \n"
"                fetch(url, { method: 'GET' })\n"
"                    .then(response => {\n"
"                        if (response.ok) {\n"
"                            console.log('Color sent successfully');\n"
"                        } else {\n"
"                            console.error('Error sending color');\n"
"                        }\n"
"                    })\n"
"                    .catch(error => console.error('Error:', error));\n"
"            });\n"
"        });\n"
"    </script>\n"
"</body>\n"
"</html>";
